services:
  - type: web
    name: construction-focus-journal
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn DjangoApp.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
