# Generated by Django 6.0.5 on 2026-05-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(unique=True)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-volume_number'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField()),
                ('publication_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='website.volume')),
            ],
            options={
                'ordering': ['volume', 'issue_number'],
                'unique_together': {('volume', 'issue_number')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(help_text='Comma-separated keywords', max_length=500)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('publication_date', models.DateField()),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='articles', to='website.author')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='website.issue')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='website.volume')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
