# Generated by Django 6.0.5 on 2026-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_articleauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Construction Focus Journal', max_length=200)),
                ('department', models.CharField(default='Department of Building', max_length=300)),
                ('faculty', models.CharField(default='Faculty of Environmental Design', max_length=300)),
                ('institution', models.CharField(default='Ahmadu Bello University Zaria, Nigeria', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('issn', models.CharField(blank=True, default='2006-0262', max_length=50)),
                ('eissn', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
