# Generated by Django 6.0.5 on 2026-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_seed_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this article in the Featured Articles section on the homepage'),
        ),
    ]
