# Generated by Django 6.0.5 on 2026-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_article_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Manuscript Length', max_length=200)),
                ('value', models.CharField(help_text='e.g. 5,000 – 12,000 words (excluding references)', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScopeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full label, shown on the About page', max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Optional shorter label for the homepage tag; falls back to Name', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(help_text='Comma-separated keywords', max_length=500)),
                ('corresponding_author_name', models.CharField(max_length=200)),
                ('corresponding_author_email', models.EmailField(max_length=254)),
                ('corresponding_author_affiliation', models.CharField(max_length=300)),
                ('corresponding_author_phone', models.CharField(blank=True, max_length=50)),
                ('manuscript_file', models.FileField(upload_to='submissions/manuscripts/')),
                ('payment_receipt', models.FileField(upload_to='submissions/receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=20)),
                ('editor_notes', models.TextField(blank=True, help_text='Internal notes, not visible to the author')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='academia_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='access_type',
            field=models.CharField(blank=True, default='Open Access', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, default='Department of Building\nFaculty of Environmental Design\nAhmadu Bello University Zaria, Nigeria'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='editor@cfjournal.org', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_response_time',
            field=models.CharField(blank=True, default='Within 2–3 business days', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.TextField(blank=True, default='Advancing knowledge in construction, infrastructure, and built environment research through rigorous peer-reviewed scholarship.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='frequency',
            field=models.CharField(blank=True, default='Quarterly', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_text',
            field=models.TextField(blank=True, default='The Construction Focus Journal A.B.U Zaria (CFJ) is a peer-reviewed academic publication dedicated to advancing the frontiers of knowledge in construction engineering, infrastructure development, and the built environment. Founded with a commitment to open-access scholarship, CFJ serves as a bridge between academic research and industry practice.\n\nOur vision is to be the leading platform for disseminating high-impact, rigorous research that shapes the future of the construction industry — embracing sustainability, digital innovation, and evidence-based practice.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Bank account details / payment steps shown on the submission page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='publisher_name',
            field=models.CharField(blank=True, default='CFJ Publishing', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='researchgate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='review_type',
            field=models.CharField(blank=True, default='Double-Blind', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='submission_fee',
            field=models.CharField(blank=True, help_text='e.g. NGN 15,000 — shown to authors before they submit', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
