# Generated by Django 6.0.5 on 2026-08-10 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_seed_scope_review_guidelines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Short teaser shown on the homepage and list page (falls back to the start of the body)', max_length=300)),
                ('body', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_posted', '-created_at'],
            },
        ),
    ]
